/** Chapters of the product walkthrough video (seconds), generated from video/src/demo-data.json. */
export const TOUR_VIDEO = {
  src: "/video/temt-tour.mp4",
  poster: "/video/temt-tour-poster.jpg",
  captions: "/video/temt-tour.vtt",
  durationSeconds: 287,
  chapters: [
    { at: 0, title: "TEMT from IIM Bangalore" },
    { at: 14, title: "The website" },
    { at: 29, title: "Getting started" },
    { at: 41, title: "Overview" },
    { at: 61, title: "Quick calculate" },
    { at: 71, title: "Calculator" },
    { at: 122, title: "Compare modes" },
    { at: 133, title: "Transport chains" },
    { at: 148, title: "Bulk import" },
    { at: 158, title: "Shipment ledger" },
    { at: 167, title: "Account and sync" },
    { at: 181, title: "Reports" },
    { at: 198, title: "Exports" },
    { at: 221, title: "Reduction planner" },
    { at: 231, title: "Factors and settings" },
    { at: 250, title: "TEMT Copilot" },
    { at: 267, title: "Guided tour" },
    { at: 272, title: "Measure your next shipment" },
  ],
} as const;
