/** Chapters of the product walkthrough video (seconds), generated from video/src/demo-data.json. */
export const TOUR_VIDEO = {
  src: "/video/temt-tour.mp4",
  poster: "/video/temt-tour-poster.jpg",
  captions: "/video/temt-tour.vtt",
  durationSeconds: 279,
  published: "2026-09-28",
  chapters: [
    { at: 0, title: "TEMT from IIM Bangalore" },
    { at: 12, title: "The website" },
    { at: 32, title: "Getting started" },
    { at: 41, title: "Overview" },
    { at: 59, title: "Quick calculate" },
    { at: 69, title: "Calculator" },
    { at: 118, title: "Compare modes" },
    { at: 128, title: "Transport chains" },
    { at: 143, title: "Bulk import" },
    { at: 155, title: "Shipment ledger" },
    { at: 164, title: "Account and sync" },
    { at: 180, title: "Reports" },
    { at: 196, title: "Exports" },
    { at: 218, title: "Reduction planner" },
    { at: 227, title: "Factors and settings" },
    { at: 246, title: "TEMT Copilot" },
    { at: 261, title: "Guided tour" },
    { at: 266, title: "Measure your next shipment" },
  ],
} as const;
