/**
 * Storage for accounts and synced workspaces.
 *
 * Every statement goes through `query(text, params)` with numbered placeholders ($1, $2, …), so user input is
 * always a bound parameter and never part of the SQL text. The SQL is a portable subset that runs unchanged on:
 *
 * - Postgres, when DATABASE_URL is set (for example a free Neon database), through node-postgres;
 * - SQLite built into Node otherwise: a file when TEMT_DATA_DIR is set, else in memory. It needs only a few MB,
 *   so it fits the smallest free hosting instances.
 *
 * Timestamps are ISO 8601 strings generated by the API, which sort correctly as text in both databases.
 */
import { mkdirSync } from "node:fs";
import { join } from "node:path";

export type StorageMode = "postgres" | "embedded-local" | "embedded-ephemeral";

export interface Db {
  mode: StorageMode;
  /** True when data survives restarts and redeploys. */
  persistent: boolean;
  query<T = Record<string, unknown>>(text: string, params?: readonly unknown[]): Promise<T[]>;
  close(): Promise<void>;
}

export interface DbOptions {
  url?: string;
  /** Folder for the embedded database file. Omit for an in-memory database. */
  dataDir?: string;
}

const MIGRATIONS = [
  `CREATE TABLE IF NOT EXISTS temt_users (
    id TEXT PRIMARY KEY,
    email TEXT NOT NULL,
    email_key TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    organisation TEXT NOT NULL DEFAULT '',
    job_title TEXT NOT NULL DEFAULT '',
    password_hash TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS temt_sessions (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES temt_users(id) ON DELETE CASCADE,
    token_hash TEXT NOT NULL UNIQUE,
    user_agent TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL,
    last_seen_at TEXT NOT NULL,
    expires_at TEXT NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS temt_sessions_user_idx ON temt_sessions (user_id)`,
  `CREATE TABLE IF NOT EXISTS temt_workspaces (
    user_id TEXT PRIMARY KEY REFERENCES temt_users(id) ON DELETE CASCADE,
    version INTEGER NOT NULL,
    data TEXT NOT NULL,
    shipments INTEGER NOT NULL,
    bytes INTEGER NOT NULL,
    device TEXT NOT NULL DEFAULT '',
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS temt_reports (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES temt_users(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    period TEXT NOT NULL,
    format TEXT NOT NULL,
    shipments INTEGER NOT NULL,
    wtw_kg DOUBLE PRECISION NOT NULL,
    created_at TEXT NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS temt_reports_user_idx ON temt_reports (user_id, created_at)`,
  `CREATE TABLE IF NOT EXISTS temt_activity (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES temt_users(id) ON DELETE CASCADE,
    kind TEXT NOT NULL,
    detail TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS temt_activity_user_idx ON temt_activity (user_id, created_at)`,
  `CREATE TABLE IF NOT EXISTS temt_login_failures (
    key TEXT NOT NULL,
    at TEXT NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS temt_login_failures_idx ON temt_login_failures (key, at)`,
];

async function postgres(url: string): Promise<Db> {
  const { default: pg } = await import("pg");
  // A small pool: the API runs on a single small instance.
  const pool = new pg.Pool({ connectionString: url, max: 4, idleTimeoutMillis: 10_000, connectionTimeoutMillis: 10_000 });
  return {
    mode: "postgres",
    persistent: true,
    async query<T>(text: string, params: readonly unknown[] = []) { return (await pool.query(text, params as unknown[])).rows as T[]; },
    close: () => pool.end(),
  };
}

async function embedded(dataDir?: string): Promise<Db> {
  const { DatabaseSync } = await import("node:sqlite");
  if (dataDir) mkdirSync(dataDir, { recursive: true });
  const sqlite = new DatabaseSync(dataDir ? join(dataDir, "accounts.sqlite") : ":memory:");
  sqlite.exec("PRAGMA foreign_keys = ON; PRAGMA journal_mode = WAL; PRAGMA busy_timeout = 5000;");
  // SQLite spells numbered parameters ?1 rather than $1; the statements are otherwise identical.
  const statements = new Map<string, ReturnType<typeof sqlite.prepare>>();
  return {
    mode: dataDir ? "embedded-local" : "embedded-ephemeral",
    persistent: !!dataDir,
    async query<T>(text: string, params: readonly unknown[] = []) {
      let statement = statements.get(text);
      if (!statement) { statement = sqlite.prepare(text.replace(/\$(\d+)/g, "?$1")); statements.set(text, statement); }
      return statement.all(...(params as (string | number | null)[])) as T[];
    },
    close: async () => sqlite.close(),
  };
}

/** Create the tables on any database that implements `query`. */
export async function migrate<T extends Db>(db: T): Promise<T> {
  for (const statement of MIGRATIONS) await db.query(statement);
  return db;
}

export async function openDb(options: DbOptions = {}): Promise<Db> {
  return migrate(options.url ? await postgres(options.url) : await embedded(options.dataDir));
}

/** Storage from the environment: DATABASE_URL, else TEMT_DATA_DIR, else in memory. */
export function dbOptionsFromEnv(env: NodeJS.ProcessEnv = process.env): DbOptions {
  const url = env.DATABASE_URL?.trim() || env.POSTGRES_URL?.trim();
  if (url) return { url };
  return { dataDir: env.TEMT_DATA_DIR?.trim() || undefined };
}
