'use client';
import Link from 'next/link';
import { useState, useMemo } from 'react';
import styles from './landing-interactions.module.css';
import { ArrowUpRight, ArrowDownRight, ArrowRight, Truck, TrainFront, Plane, Ship, Info, Factory, Package, Pill, CarFront, Check, Play, RotateCcw, Database, FileSpreadsheet, GitBranch, FileCheck2 } from 'lucide-react';
import { compareFreightMix, FACTORS } from '@temt/calculator/preview';
import type { AnalysisResult, Mode, ShipmentLeg } from '@temt/calculator';

const number = (n:number, digits=0)=>new Intl.NumberFormat('en-IN',{maximumFractionDigits:digits,minimumFractionDigits:digits}).format(n);

export function HeroSimulator() {
  const [tonnes,setTonnes]=useState(1000);
  const [km,setKm]=useState(1000);
  const [rail,setRail]=useState(30);
  const [info,setInfo]=useState(false);
  const result=useMemo(()=>compareFreightMix(tonnes,km,rail),[tonnes,km,rail]);
  return <div className="hero-simulator" id="quick-estimate">
    <div className="simulator-top"><span className="eyebrow">A SMALL SHIFT. A VISIBLE DIFFERENCE.</span><span className="live-tag"><i/> INTERACTIVE</span></div>
    <div className="simulator-heading"><h2>What if you<br />changed the mix?</h2><span className="sim-index">01<span>/04</span></span></div>
    <div className="sim-inputs"><label>Monthly freight<input type="number" aria-label="Monthly freight in tonnes" value={tonnes} min={1} max={1000000} step={100} onChange={e=>setTonnes(Math.max(1,Math.min(1000000,Number(e.target.value)||1)))}/><span>tonnes</span></label><label>Average haul<input type="number" aria-label="Average haul in kilometres" value={km} min={1} max={20000} step={100} onChange={e=>setKm(Math.max(1,Math.min(20000,Number(e.target.value)||1)))}/><span>km</span></label></div>
    <div className="rail-label"><label htmlFor="rail-share">Move road freight to rail</label><span>{rail}<small>%</small></span></div>
    <input id="rail-share" className="rail-slider" type="range" min={0} max={100} step={5} value={rail} onChange={e=>setRail(Number(e.target.value))} style={{'--range':`${rail}%`} as React.CSSProperties}/>
    <div className="range-endpoints"><span>100% ROAD</span><span>100% RAIL</span></div>
    <div className="comparison-bars"><div><span>All road</span><i><b style={{width:'100%'}}/></i><strong>{number(result.baselineKg/1000,2)} t</strong></div><div><span>Your mix</span><i><b className="mix-bar" style={{width:`${result.scenarioKg/result.baselineKg*100}%`}}/></i><strong>{number(result.scenarioKg/1000,2)} t</strong></div></div>
    <div className="sim-result" aria-live="polite" aria-atomic="true"><div><span className="eyebrow">POTENTIAL MONTHLY REDUCTION</span><div className="result-number"><span key={result.savedKg} className={styles.resultValue}>{number(result.savedKg/1000,2)}</span><span>tCO₂e</span></div></div><span className="reduction-badge"><ArrowDownRight size={18}/>{number(result.reductionPercent,1)}%</span></div>
    <div className="sim-bottom"><button type="button" onClick={()=>setInfo(!info)} aria-expanded={info} aria-controls="hero-assumptions"><Info size={14}/> Illustrative estimate <span>{info?'−':'+'}</span></button><Link prefetch={false} href={`/demo/?rail=${rail}`}>Explore scenario <ArrowUpRight size={14}/></Link></div>
    {info&&<div id="hero-assumptions" className="sim-assumptions">Equal-distance illustration using GLEC v3.2 India road (0.0663) and rail (0.0106) kgCO₂e/t-km. Excludes first/last-mile legs and terminals. The rail share is an assumption, not a routing recommendation. <Link prefetch={false} href="/methodology/">View methodology</Link>.</div>}
  </div>;
}

const modes = [
  {id:'road', label:'Road', Icon:Truck, code:'01', factor:'road-hcv', title:'The backbone of your network.', text:'Put a number on your road freight. Start with India-specific heavy commercial vehicle factors, then understand the footprint of each leg.', detail:'INDIA · DIESEL HCV · 30–50t GVW', origin:'Distribution centre', destination:'Regional warehouse'},
  {id:'rail', label:'Rail', Icon:TrainFront, code:'02', factor:'rail-india', title:'A different track. A different footprint.', text:'Explore the impact of moving freight by rail. Compare India’s average mixed-traction intensity against your road baseline.', detail:'INDIA · MIXED DIESEL / ELECTRIC', origin:'Origin rail terminal', destination:'Destination rail terminal'},
  {id:'air', label:'Air', Icon:Plane, code:'03', factor:'air-short', title:'Make the trade-off visible.', text:'When speed matters, understand the carbon intensity behind it. Explicit short-haul and long-haul profiles keep the estimate transparent.', detail:'GLOBAL · SHORT-HAUL MIX · UP TO 1,500km', origin:'Origin airport', destination:'Destination airport'},
  {id:'ocean', label:'Ocean', Icon:Ship, code:'04', factor:'ocean-container', title:'Across the water. Into the detail.', text:'Account for the ocean leg with a regional dry-container factor. Carry the loading assumption with the result, from port to report.', detail:'MIDDLE EAST / INDIA · DRY CONTAINER · 10t/TEU', origin:'Origin port', destination:'Destination port'},
] as const;

export function ModeExplorer() {
  const [selected,setSelected]=useState<Mode>('road');
  const active=modes.find(m=>m.id===selected)!;
  const [distance,setDistance]=useState(1000);
  const Icon=active.Icon;
  const emission=20*distance*FACTORS[active.factor].kgCO2ePerTonneKm;
  return <div className="mode-explorer"><div className="mode-tabs" role="tablist" aria-label="Freight modes">{modes.map(m=><button key={m.id} id={`tab-${m.id}`} type="button" role="tab" aria-selected={selected===m.id} aria-controls="mode-content" className={selected===m.id?'active':''} onClick={()=>setSelected(m.id)} onKeyDown={e=>{if(['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();const i=modes.findIndex(x=>x.id===selected);const next=modes[(i+(e.key==='ArrowRight'?1:3))%4].id;setSelected(next);document.getElementById(`tab-${next}`)?.focus();}}}><span>{m.code}</span><m.Icon size={23} strokeWidth={1.4}/><strong>{m.label}</strong><ArrowUpRight size={16}/></button>)}</div><div id="mode-content" className="mode-content" role="tabpanel" aria-labelledby={`tab-${active.id}`}><div className="mode-description"><p className="eyebrow">{active.detail}</p><h3>{active.title}</h3><p>{active.text}</p><Link prefetch={false} className="text-link" href={`/demo/?mode=${active.id}`}>Explore {active.label.toLowerCase()} emissions <ArrowUpRight size={17}/></Link></div><div className={`transport-visual transport-${active.id}`}><div className="transport-top"><span className="eyebrow">EQUAL-DISTANCE ILLUSTRATION</span><span>20 TONNES</span></div><div className="route-line"><span className="route-node"/><div key={active.id} className={`route-vehicle ${styles.routeVehicle}`}><Icon size={61} strokeWidth={1}/></div><span className="route-node end"/><span className="route-dashes"/></div><div className="route-labels"><span>{active.origin}</span><span>{active.destination}</span></div><div className="route-result"><div><label htmlFor="mode-distance">Distance</label><select id="mode-distance" value={distance} onChange={e=>setDistance(Number(e.target.value))}><option value={500}>500 km</option><option value={1000}>1,000 km</option><option value={1500}>1,500 km</option></select></div><div><span>ILLUSTRATIVE WTW EMISSIONS</span><strong>{number(emission,0)} <small>kgCO₂e</small></strong></div></div></div></div></div>;
}

const sectors = [
  {id:'automotive',Icon:CarFront,label:'Automotive',headline:'Every component has a journey.',copy:'See how inbound components and outbound vehicles contribute to your network footprint. Compare a road-heavy mix with a rail-led alternative.',route:'SUPPLIERS → ASSEMBLY → DISTRIBUTION',metric:'Multi-leg',metricLabel:'INBOUND & OUTBOUND FLOWS',profiles:['Supplier consolidation','Plant-to-warehouse movements','Modal-shift scenarios']},
  {id:'fmcg',Icon:Package,label:'FMCG',headline:'Many deliveries. One clear view.',copy:'Connect recurring distribution runs into a monthly view. Identify high-activity routes and compare subsidiary footprints on the same basis.',route:'FACTORY → DISTRIBUTION → REGIONAL HUB',metric:'Network-wide',metricLabel:'DISTRIBUTION VISIBILITY',profiles:['Regional distribution','Recurring freight activity','Subsidiary comparisons']},
  {id:'materials',Icon:Factory,label:'Industrial materials',headline:'Big volumes. Meaningful choices.',copy:'Explore the effect of bulk freight volumes and longer hauls. Test road-to-rail allocations before discussing operational feasibility.',route:'SOURCE → PROCESSING → CUSTOMER',metric:'Tonne-km',metricLabel:'ACTIVITY-BASED ACCOUNTING',profiles:['Bulk materials movement','Heavy freight profiles','Long-haul alternatives']},
  {id:'pharma',Icon:Pill,label:'Pharmaceuticals',headline:'When priority meets accountability.',copy:'Understand the difference between time-sensitive air movements and surface transport. Make assumptions visible for every shipment.',route:'PRODUCTION → AIR CARGO → DISTRIBUTION',metric:'Mode-level',metricLabel:'EMISSIONS INTENSITY',profiles:['Priority air shipments','Surface distribution','Explicit haul profiles']},
] as const;
export function SectorExplorer() {
  const [sector,setSector]=useState<(typeof sectors)[number]>(sectors[0]);
  return <div className="sector-explorer"><div className="sector-tabs" role="tablist" aria-label="Industry scenarios">{sectors.map(s=><button key={s.id} type="button" role="tab" id={`sector-${s.id}`} aria-controls="sector-panel" aria-selected={sector.id===s.id} className={sector.id===s.id?'active':''} onClick={()=>setSector(s)}><s.Icon size={18}/>{s.label}</button>)}</div><div className="sector-panel" role="tabpanel" id="sector-panel" aria-labelledby={`sector-${sector.id}`}><div className="sector-panel-copy"><p className="eyebrow">{sector.route}</p><h3>{sector.headline}</h3><p>{sector.copy}</p><Link prefetch={false} href={`/demo/?sector=${sector.id}`} className="button button-dark">Try the {sector.label.toLowerCase()} scenario <ArrowUpRight size={17}/></Link><p className="small-note">Illustrative activity. No company-reported data.</p></div><div className="sector-panel-detail"><sector.Icon size={46} strokeWidth={1}/><h4>{sector.metric}</h4><span className="eyebrow">{sector.metricLabel}</span><ul>{sector.profiles.map(p=><li key={p}><Check size={15}/>{p}</li>)}</ul><div className="sector-nifty"><span>NIFTY 500</span><Link prefetch={false} href={`/demo/?sector=${sector.id}#company`}>Find your company <ArrowUpRight size={14}/></Link></div></div></div></div>;
}

const pipelineRows: ShipmentLeg[]=[{shipmentId:'TEMT-001',legIndex:1,date:'2026-08-12',subsidiary:'Western region',mode:'road',profile:'road-hcv',tonnes:20,kilometres:780},{shipmentId:'TEMT-002',legIndex:1,date:'2026-08-13',subsidiary:'Western region',mode:'road',profile:'road-hcv',tonnes:24,kilometres:60},{shipmentId:'TEMT-002',legIndex:2,date:'2026-08-13',subsidiary:'Western region',mode:'rail',profile:'rail-india',tonnes:24,kilometres:1040}];
export function PipelinePreview(){
  const [ran,setRan]=useState(false);
  const [result,setResult]=useState<AnalysisResult|null>(null);
  const [loading,setLoading]=useState(false);
  const [error,setError]=useState('');
  const run=async()=>{setLoading(true);setError('');try{const {analyze}=await import('@temt/calculator');setResult(analyze(pipelineRows));setRan(true);}catch{setError('The calculation engine could not be loaded. Please try again.');}finally{setLoading(false);}};
  return <div className="pipeline-preview"><div className="pipeline-title"><div><FileSpreadsheet size={18}/><span>shipment_preview.csv</span></div><span className="sample-label">SAMPLE DATA</span></div><div className="mini-sheet"><div className="mini-sheet-head"><span>SHIPMENT</span><span>MODE</span><span>LOAD</span><span>DISTANCE</span></div>{pipelineRows.map(r=><div key={`${r.shipmentId}-${r.legIndex}`}><span>{r.shipmentId}<small> / {r.legIndex}</small></span><span>{r.mode}</span><span>{r.tonnes} t</span><span>{number(r.kilometres)} km</span></div>)}</div><div className="pipeline-stages">{[{Icon:Database,label:'Validate',detail:'3 records'},{Icon:GitBranch,label:'Calculate',detail:'GLEC v3.2'},{Icon:FileCheck2,label:'Aggregate',detail:'2 shipments'}].map((s,i)=><div key={s.label} className={ran?'stage-complete':''}><span className="stage-icon">{ran?<Check size={18}/>:<s.Icon size={19}/>}</span><strong>{s.label}</strong><small>{s.detail}</small>{i<2&&<ArrowRight className="stage-arrow" size={16}/>}</div>)}</div><div className="pipeline-output" aria-live="polite">{error?<><span role="alert">{error}</span><strong>Ready to retry.</strong></>:ran&&result?<><span>3 legs accepted · {result.totals.shipmentCount} shipments</span><strong>{number(result.totals.emissionsKg,2)} <small>kgCO₂e</small></strong><span>Calculated locally with published factors</span></>:<><span>Ready when you are.</span><strong>See the process.</strong><span>Run a real calculation on these sample records.</span></>}</div><button type="button" onClick={ran?()=>{setRan(false);setResult(null);}:run} className="pipeline-run" disabled={loading}>{loading?<><RotateCcw size={16} className={styles.loading}/> Loading calculation engine</>:ran?<><RotateCcw size={16}/> Reset sample</>:<><Play size={16}/> Run sample pipeline</>}<span>{ran?'CALCULATION COMPLETE':'3 ROWS · NO SIGN-UP'}</span></button></div>;
}
