'use client';
import Link from 'next/link';
import { useState } from 'react';
import { ArrowUpRight, Menu, X } from 'lucide-react';

export function Header({compact=false}:{compact?:boolean}) {
  const [open,setOpen]=useState(false);
  return <header className="site-header"><div className="page-width header-inner"><Link prefetch={false} className="brand" href="/" aria-label="TEMT home"><span className="brand-symbol" aria-hidden="true"><i/><i/><i/></span><span>TEMT<span className="brand-dot">.</span></span></Link><span className="preview-label">ENTERPRISE PREVIEW</span><nav aria-label="Main navigation" className={open?'main-nav nav-open':'main-nav'}><a href="/#platform" onClick={()=>setOpen(false)}>Platform</a><a href="/#industries" onClick={()=>setOpen(false)}>For enterprises</a><Link prefetch={false} href="/methodology/" onClick={()=>setOpen(false)}>Methodology</Link></nav><a className="header-login" href="https://iimb.freightemissions.com/login">Sign in <ArrowUpRight size={13}/></a><Link prefetch={false} className="button button-dark header-cta" href={compact?'/':'/demo/'}>{compact?'Back to overview':'Explore the demo'}<ArrowUpRight size={16}/></Link><button type="button" className="mobile-menu" aria-label={open?'Close navigation':'Open navigation'} aria-expanded={open} onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div></header>;
}
export function Footer() {
  return <footer className="site-footer"><div className="page-width"><div className="footer-main"><div><Link prefetch={false} className="brand footer-brand" href="/">TEMT<span className="brand-dot">.</span></Link><p>Freight decisions.<br/>Backed by carbon data.</p></div><div className="footer-links"><Link prefetch={false} href="/demo/">Interactive demo</Link><Link prefetch={false} href="/methodology/">Methodology & sources</Link><a href="https://iimb.freightemissions.com/register">Access production TEMT <ArrowUpRight size={13}/></a><a href="https://dpiit.freightemissions.com/">DPIIT product <ArrowUpRight size={13}/></a><Link prefetch={false} href="/privacy/">Preview privacy</Link><a href="mailto:aditya.gupta@iimb.ac.in">Contact the team <ArrowUpRight size={13}/></a></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} TEMT enterprise product preview</span><p>Authorized product preview. Interactive scenarios use sample data and a separate demonstration engine. Institutional certifications refer to the existing TEMT product and their stated scope.</p><span>BUILT FOR A LOWER-CARBON JOURNEY <span className="status-dot"/></span></div></div></footer>;
}
